# Site settings
title: Robert's Blog
email: robertquitt@berkeley.edu
description: Tech and various ramblings
baseurl: ""
url: ""
twitter_username:
github_username:  robertquitt

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

# Build settings
markdown: kramdown

