# Site settings
title: Robert's Homepage
email: robertquitt@berkeley.edu
description: Robert's personal blog
baseurl: ""
url: ""
twitter_username: coocoohead39
github_username:  robertquitt

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Build settings
markdown: kramdown

